"""
Adds an "answer" field to each question in the TCH 206 theory bank
(question_banks table, question_type='theory'). Safe to re-run: it
reads the current row, merges in answers by id, and writes the whole
questions array back — running it twice just overwrites the same
answer text.

Usage:
    python add_theory_answers_tch206.py
"""

import os

from dotenv import load_dotenv
from supabase import create_client

load_dotenv()

SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_SERVICE_KEY = os.environ["SUPABASE_SERVICE_KEY"]

supabase = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)

COURSE_CODE = "TCH 206"

ANSWERS = {
    1: "Descriptive statistics summarises and organises data you already have (means, plots, tables) — e.g. reporting the average reactor temperature over a shift. Inferential statistics uses a sample to draw conclusions about a wider population — e.g. testing whether a new catalyst batch changes yield across all future production runs. Inference needs more caution because it involves uncertainty and sampling error: a descriptive claim is just arithmetic on data in hand, but an inferential claim is a probabilistic generalisation that can be wrong even when correctly calculated.",
    2: "A population is the entire set of items of interest (all units ever produced); a sample is the subset actually measured. A parameter is a fixed numerical property of the population (true mean \\(\\mu\\)); a statistic is the corresponding value computed from the sample (\\(\\bar{x}\\)), which varies from sample to sample. This distinction matters because inferential statistics is entirely about using a variable statistic to estimate an unknown fixed parameter, with quantified uncertainty.",
    3: "For {2,3,4} and {2,3,10}, the mean jumps from 3 to 5 because the single outlier (10) pulls it toward itself, while the median stays at 3 in both cases since it only depends on the middle-ranked value. The mean is \"not robust\" because every value enters the calculation with equal weight, so one extreme point can dominate; the median is robust because it depends only on rank order. Practically, for skewed process data, the median gives a more representative \"typical\" value, while the mean can be distorted by rare extremes.",
    4: "The IQR fence method flags anything outside \\([Q_1-1.5\\,IQR,\\ Q_3+1.5\\,IQR]\\) — simple and robust to non-normality, but the 1.5 multiplier is arbitrary and can mislabel points in heavily skewed data. The 3σ edit rule flags anything beyond 3 standard deviations from the mean — intuitive, but the mean and SD it depends on are themselves distorted by the outliers being searched for. The Hampel identifier uses the median and MAD instead, making it far more robust to multiple outliers, but is more computationally involved and less familiar to non-specialists.",
    5: "Statistics condenses data into numbers (mean, variance, correlation) that answer \"how much\" a quantity is or how strongly two things relate. Visualisation shows the shape, spread, and structure of the data, answering \"what does it look like.\" An engineer needs both because summary numbers can hide structure — very different datasets can share identical means and variances while looking completely different on a plot. If only mean and variance are reported, a bimodal distribution, a trend, or a cluster of outliers can go completely undetected.",
    6: "A bar chart displays categorical data, with bars representing counts or values for discrete categories with no inherent numeric ordering between bars. A histogram displays continuous numeric data grouped into bins, where bar width and adjacency carry meaning (the x-axis is a continuous scale). A histogram reveals the shape of the distribution — skewness, modality, and spread — none of which a single mean and standard deviation can show, since two very differently-shaped distributions can share the same mean and SD.",
    7: "Common cause variation is the natural, inherent noise of a stable process. Special cause variation is an unusual, assignable disturbance (a machine fault, a raw material change) that pushes the process outside its normal pattern. The Nelson Rules are pattern tests applied to a control chart (points outside 3σ, runs on one side of the centre line, trends, etc.) that help distinguish genuine special-cause signals from ordinary common-cause noise, so an engineer doesn't over-react to normal fluctuation or under-react to a real problem.",
    8: "A correlation matrix / heat map displays the pairwise correlation coefficients between many variables at once, with colour intensity indicating strength and direction of association. In root-cause analysis, it quickly highlights which process variables move together with a defect or failure mode. In feature selection/multicollinearity detection for regression, it reveals predictor variables highly correlated with each other, warning that including both would make coefficient estimates unstable.",
    9: "Gross errors are large, one-off mistakes (misread instrument, transcription error) caused by human or equipment blunders, managed by careful procedure and data screening. Systematic errors are consistent, repeatable biases in one direction (a miscalibrated sensor reading consistently high), corrected through calibration. Random errors are unpredictable small fluctuations from many minor uncontrolled influences, managed statistically by averaging repeated measurements, since their effects tend to cancel out.",
    10: "Accuracy is how close measurements are to the true value; precision is how close repeated measurements are to each other. Using the target-shooting analogy, a tight cluster of shots far from the bullseye is precise but not accurate, while shots scattered around the bullseye are accurate on average but not precise. Yes — an instrument can be precise but not accurate, e.g. a scale that reads consistently 2 kg high on every measurement: repeatable but systematically wrong.",
    11: "In words, the formula says the variance of an output \\(y=f(x_1,x_2,\\dots)\\) is approximately the sum, over each input variable, of (how sensitive \\(y\\) is to that variable, \\(\\partial f/\\partial x_i\\)) squared, times the variance of that variable. It's a first-order approximation of how uncertainty in each input propagates to uncertainty in the output. Variances add rather than standard deviations because variances represent independent sources of \"spread\" that combine additively, whereas standard deviations do not have this additive property for independent variables.",
    12: "The frequentist interpretation defines probability as the long-run relative frequency of an event over many repeated trials — e.g. \"this valve fails in 2% of all operating cycles,\" estimated by observing many cycles. The Bayesian interpretation treats probability as a degree of belief that can be updated with new evidence — e.g. \"given what we know so far, there's a 70% chance this specific batch is off-spec,\" a statement about one particular case, updated as more test results come in.",
    13: "The general additive rule is \\(P(A\\cup B)=P(A)+P(B)-P(A\\cap B)\\). It subtracts the intersection because outcomes belonging to both A and B get counted once in \\(P(A)\\) and once again in \\(P(B)\\), so without subtraction they would be double-counted. It reduces to simple addition when A and B are mutually exclusive, i.e. \\(P(A\\cap B)=0\\).",
    14: "With a 2% true failure rate, 95% true-positive rate, and 10% false-positive rate, Bayes' theorem combines the prior (2% failure) with the test's reliability to get the posterior probability of actual failure given a positive result. Because failures are rare, most positive test results actually come from the much larger pool of healthy pumps falsely flagged, rather than from the small pool of truly failing pumps correctly flagged. This is why the posterior probability of true failure given a positive test is much lower than the 95% detection rate alone would suggest — the base rate dominates the result.",
    15: "The binomial distribution models the number of successes in a fixed number of independent trials, each with the same success probability \\(p\\). The Poisson distribution models the number of events occurring in a fixed interval of time or space, when events happen independently at a constant average rate \\(\\lambda\\). The binomial can be approximated by the Poisson when \\(n\\) is large and \\(p\\) is small, such that \\(np\\) stays moderate.",
    16: "Expected value is the long-run average outcome a process would produce if repeated indefinitely under the same probabilistic conditions — the \"centre of mass\" of all possible outcomes weighted by their probability. In process economics/risk analysis, it's used to compute the average expected profit or loss across uncertain scenarios. In reactor engineering/yield optimisation, it's used to estimate expected yield across variable feedstock or operating conditions, guiding design choices that maximise average performance.",
    17: "Ordinary Least Squares (OLS) estimates parameters by minimising the sum of squared residuals, with no explicit probability model required. Maximum Likelihood Estimation (MLE) chooses parameters that make the observed data most probable under an assumed distribution. Bayesian Estimation combines a prior belief about parameters with the observed data to produce a posterior distribution. OLS and MLE coincide when the errors are assumed independent and normally distributed with constant variance.",
    18: "The five-step hypothesis testing framework is: (1) state the null and alternative hypotheses, (2) choose a significance level \\(\\alpha\\), (3) select and compute an appropriate test statistic, (4) determine the critical value or p-value, and (5) make a decision. A one-tailed test checks for a difference in only one specified direction, while a two-tailed test checks for a difference in either direction, splitting the significance level across both tails.",
    19: "A Type I error is rejecting a true null hypothesis (a false alarm). A Type II error is failing to reject a false null hypothesis (a missed detection). Both probabilities can't be driven to zero simultaneously with a fixed sample size because tightening the criterion to avoid one type of error automatically increases the risk of the other; reducing both together requires more data, not just a stricter threshold.",
    20: "Statistical significance means an observed difference is unlikely to be due to chance alone, given the sample size and variability. Practical/engineering significance asks whether that difference is large enough to actually matter in application. A yield shift from 85.00% to 85.02% could be statistically significant with a very large sample, yet be practically meaningless — illustrating that statistical significance alone doesn't imply real-world importance.",
    21: "A confidence interval for the mean is symmetric because it's built from the normal (or t) distribution, which is symmetric around the sample mean. A confidence interval for the variance is asymmetric because it's built from the chi-square distribution, which is skewed (bounded below by zero, unbounded above), so the interval's bounds are not equidistant from the point estimate.",
    22: "ANOVA's core logic is that if group means truly differ, the variability between group means will be large relative to the variability within groups (natural noise). By comparing these two variance components via an F-ratio, ANOVA tests whether the \"signal\" (between-group variation) is large compared to the \"noise\" (within-group variation). A significant F-ratio indicates the signal is too large to be explained by noise alone, implying the group means genuinely differ.",
    23: "ANOVA assumes independence of observations, normality of residuals/within-group values, and equal variances across groups. If independence is violated, the test becomes overconfident, inflating false-positive risk. If normality is badly violated with small samples, p-values become unreliable. If variances differ greatly between groups, the F-test can be misleading, since it assumes a single pooled within-group variance.",
    24: "The regression F-test compares the variance explained by the regression model (\\(SS_{Reg}\\), the \"signal\") against the variance left unexplained (\\(SS_{Error}\\), the \"noise\"). This mirrors the one-way ANOVA logic exactly: it asks whether the explained variation is large relative to the unexplained variation, indicating the regression model captures real structure rather than fitting noise.",
    25: "Regression exists as an empirical alternative because first-principles modelling requires a full theoretical understanding of the underlying physics/chemistry, which is often unavailable, too complex, or too costly to derive. Regression instead builds a statistical relationship directly from observed input-output data, without needing to know the exact governing mechanism — useful when a \"good enough\" predictive model is needed faster, at the cost of the model only being valid within the range of data it was fitted on.",
    26: "Simple linear regression assumes: linearity, independence (residuals not correlated with each other), constant variance/homoscedasticity, and normality of residuals. Linearity is checked via a scatter or residual-vs-fitted plot for curvature; independence via a residuals-vs-order plot; constant variance via a residual-vs-fitted plot for a \"funnel\" shape; and normality via a Q-Q plot or histogram of residuals.",
    27: "The ANOVA decomposition \\(SST=SSR+SSE\\) splits the total variation in y into the part explained by the regression (\\(SSR\\)) and the part left as residual error (\\(SSE\\)). \\(R^2=SSR/SST\\) is the proportion of total variation explained. The F-test compares \\(SSR\\) to \\(SSE\\) (accounting for degrees of freedom) to test whether the model explains significantly more variation than chance alone. \\(R^2\\) alone doesn't indicate significance because it can be inflated by adding predictors without the improvement being statistically reliable.",
    28: "The residual-diagnostics workflow includes: residual analysis (residuals vs. fitted values), a normality check (Q-Q plot or histogram), an independence check (residuals vs. order/time), outlier detection, and cross-validation. A \"funnel-shaped\" residual plot — where the spread widens or narrows systematically as fitted values increase — indicates heteroscedasticity, undermining the validity of standard error estimates.",
    29: "For \\(y=ae^{bx}\\), taking the natural log of both sides gives \\(\\ln y=\\ln a+bx\\), linear in \\(x\\) with slope \\(b\\) and intercept \\(\\ln a\\) — so OLS can be applied directly to the transformed variables and converted back. This trick doesn't apply to every nonlinear model because it requires the equation to be reducible to a linear form through a monotonic transformation; the Antoine equation is nonlinear in its parameters in a way that cannot be untangled by a simple log transform, so nonlinear regression methods are required instead.",
    30: "Minimising \\(S(\\boldsymbol\\beta)=(\\mathbf y-\\mathbf X\\boldsymbol\\beta)^T(\\mathbf y-\\mathbf X\\boldsymbol\\beta)\\) means finding the \\(\\boldsymbol\\beta\\) that makes this expression as small as possible. Taking the derivative with respect to \\(\\boldsymbol\\beta\\) and setting it to zero produces the normal equations \\((\\mathbf X^T\\mathbf X)\\hat{\\boldsymbol\\beta}=\\mathbf X^T\\mathbf y\\). In words, this says the best-fit coefficients make the residual vector orthogonal to every column of \\(\\mathbf X\\) — the geometric condition for the closest possible least-squares fit.",
    31: "Yes, a model can have a significant overall F-test but an insignificant t-test for one particular predictor. The overall F-test asks whether the predictors jointly explain a significant amount of variation, while each t-test asks whether that one specific predictor contributes uniquely beyond what the others already explain. This commonly happens under multicollinearity: correlated predictors may jointly explain a lot (significant F), but individually neither may show a significant unique contribution once the other is in the model.",
    32: "A prediction interval for a new observation must account for uncertainty in estimating the true mean response, plus the additional inherent random scatter of an individual new data point around that mean. This second term is why the formula includes an extra \"+1\" inside the square root — it adds one full unit of residual variance on top of the estimation uncertainty, making the prediction interval always wider than the confidence interval for the mean at the same point.",
    33: "The matrix-method workflow proceeds: (1) construct the design matrix \\(\\mathbf X\\) from the predictor variables with a column of ones for the intercept, and the response vector \\(\\mathbf y\\); (2) solve the normal equations for the coefficient estimates; (3) compute residuals and check diagnostic plots; (4) run the ANOVA/F-test and t-tests for each coefficient; (5) compute \\(R^2\\) and adjusted \\(R^2\\); and (6) construct a confidence interval on a coefficient of interest using its standard error and the appropriate t-distribution.",
    34: "Multicollinearity is when two or more predictor variables in a regression are highly correlated with each other. It's a concern because it makes individual coefficient estimates unstable and their standard errors inflated, even though the model's overall predictive fit may still be fine. A correlation matrix helps detect it before fitting a model by flagging pairs of predictors with high pairwise correlation.",
    35: "Polynomial regression and multiple linear regression are not fundamentally different — polynomial regression is a special case of multiple linear regression where the \"extra predictors\" are powers of a single variable (\\(x, x^2, x^3,\\dots\\)) rather than genuinely distinct measured variables. In both cases, the design matrix is built from columns representing each term, and the same matrix least-squares machinery is used to estimate the coefficients.",
    36: "The source distinguishes \"regression\" (typically associated with the formal statistical framework — hypothesis tests, confidence intervals, assumption checking) from \"curve fitting\" (a more general, informal term for fitting any mathematical function to data). In practice, chemical engineers treat them interchangeably because the underlying mathematics (least-squares parameter estimation) is identical; the distinction is mostly one of framing and rigor rather than technique.",
    37: "DoE was developed as much as a resource problem as a statistical one because running experiments is expensive and time-consuming, so poorly planned experimentation wastes limited resources. The five things it was designed to achieve are: extracting maximum information from a minimum number of runs, separating and quantifying the effects of multiple factors simultaneously, detecting interactions between factors, controlling for uncontrolled sources of variation, and providing a statistically defensible basis for conclusions.",
    38: "Best-Guess/Trial-and-Error relies on intuition with no formal structure, so it's unsystematic and hard to reproduce. One-Factor-at-a-Time (OFAT) varies a single factor while holding others fixed — simple, but structurally cannot detect interaction effects, because it never varies two factors together: testing temperature alone and catalyst concentration alone will miss the case where their combination produces a disproportionate yield change neither reveals alone. Factorial Experimentation varies all factors simultaneously across designed combinations, allowing both main effects and interactions to be estimated.",
    39: "The three statistical pillars of DoE are randomization (preventing unknown variables from systematically biasing results), replication (independently repeating the entire experimental run to estimate true experimental error), and blocking (grouping runs by a known nuisance factor to remove its effect). Replication differs from a duplicate measurement because a duplicate measures the same run twice (capturing only measurement error), while replication reruns the entire experiment independently (capturing full run-to-run process variability).",
    40: "The three historical eras of DoE are: the Agricultural era, led by Ronald Fisher, who introduced randomization, blocking, and factorial designs; the Industrial era, led by George Box, who adapted DoE for manufacturing and process optimisation, including response surface methodology; and the Quality era, led by Genichi Taguchi, who emphasised robust design for quality engineering. The vocabulary isn't arbitrary because terms like \"block\" and \"yield\" originated in agricultural field trials and carried through into industrial DoE terminology.",
    41: "Coded variables are used instead of actual factor values because they make the design symmetric and comparable across factors measured in different units, simplify the mathematics of computing effects and interactions, reduce numerical/multicollinearity problems from hugely different raw magnitudes, and make the resulting coefficients directly interpretable as the effect of moving from the low to the high level of a factor, regardless of its original physical units.",
    42: "In the \\(2^3\\) screening example, a main effect for a factor is the average response when that factor is high minus the average response when it's low, averaged over all combinations of the other factors. An interaction effect uses the appropriate contrast to isolate how the effect of one factor changes depending on the level of another. The percent-contribution table shows what fraction of total variability each effect accounts for, helping decide which factors carry forward into RSM optimisation.",
    43: "Central Composite Design (CCD) uses five levels per factor (including axial points) and can be built sequentially, but can include extreme conditions beyond the original factorial range, which may be impractical or unsafe. Box–Behnken Design (BBD) uses only three levels per factor and never combines all factors at extreme levels simultaneously, avoiding extreme corner conditions — the safer choice when extreme combinations are impractical or dangerous, though less naturally sequential than CCD.",
    44: "Mixture designs require specialised Scheffé polynomial models because the factors (ingredient proportions) must always sum to 1, so changing one proportion necessarily forces the others to change too. Standard factorial designs assume factors can be varied independently, which is physically impossible in a mixture context; the sum-to-one constraint means the design space is a simplex rather than an independent hypercube, requiring Scheffé's specially formulated polynomials.",
    45: "The full workflow includes: estimating model coefficients via matrix OLS, a Pareto chart ranking effect magnitudes, an ANOVA/F-test for overall significance, Adjusted \\(R^2\\) and Predicted \\(R^2\\) (via leave-one-out validation), and the four standard diagnostic residual plots. If Predicted \\(R^2\\) is much lower than Adjusted \\(R^2\\), it signals overfitting — the model fits existing data well but doesn't generalise, often from too many terms relative to the data available.",
    46: "Advantages of DoE include efficient use of experimental resources, detecting interaction effects OFAT misses, and a statistically defensible basis for conclusions. Limitations include the need for careful upfront planning and assumptions that may not hold. \"Poor planning at the design stage can invalidate the entire result\" because DoE's statistical power comes from the structure of the design itself — if important factors are omitted or effects are confounded, no amount of correct downstream analysis can recover information the experiment never captured.",
}


def main():
    bank = (
        supabase.table("question_banks")
        .select("id, questions")
        .eq("course_code", COURSE_CODE)
        .eq("question_type", "theory")
        .execute()
    )

    if not bank.data:
        print(f"No theory bank found for {COURSE_CODE}.")
        return

    row = bank.data[0]
    questions = row["questions"]

    updated = 0
    for question in questions:
        answer = ANSWERS.get(question["id"])
        if answer:
            question["answer"] = answer
            updated += 1

    supabase.table("question_banks").update(
        {"questions": questions}
    ).eq("id", row["id"]).execute()

    print(f"Updated {updated} / {len(questions)} questions with answers for {COURSE_CODE}.")


if __name__ == "__main__":
    main()