"""
Upserts course outlines for the CCMAS course expansion batch into
public.course_outlines. Safe to re-run: uses course_code (the table's
primary key) as the upsert conflict target, so running this twice
just updates the same 42 rows rather than duplicating them.

Usage:
    python import_ccmas_course_outlines.py
"""

import os

from dotenv import load_dotenv
from supabase import create_client

load_dotenv()

SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_SERVICE_KEY = os.environ["SUPABASE_SERVICE_KEY"]

supabase = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)


OUTLINES = [
    {"course_code": "BME 102", "official_title": "Introduction to Biomedical Engineering", "level": 100, "semester": None, "units": 2, "concise_description": "Overview of biomedical engineering, impact of technology on biology and medicine, human system as a living machine, and health technology practice.", "ordered_topics": ["Bio- and Medical Engineering: impacts of technology on biology and medicine", "Biomedical engineering: definition, history, and components", "Biomedical engineering and health technology", "Human system: man as a living machine", "Human system and instrumentation research", "Development, education and training in biomedical engineering", "Certification and practice of biomedical engineering", "Health technology practice in Nigeria", "Problems and prospects of biomedical engineering in Nigeria", "Problems and prospects of health technology in Africa"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "partially_verified"},
    {"course_code": "CEE 101", "official_title": "Introduction to Civil Engineering", "level": 100, "semester": None, "units": 1, "concise_description": "History of civil engineering, branches, roles of civil engineers in government, industry and academia, career opportunities and professional bodies.", "ordered_topics": ["History of civil engineering", "Branches of civil engineering", "Roles of civil engineers in government", "Roles of civil engineers in industry", "Roles of civil engineers in academia", "Allied professionals and interaction with civil engineers", "Career opportunities in civil engineering", "Professional and regulatory bodies"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "CPE 112", "official_title": "Introduction to Computer Engineering", "level": 100, "semester": None, "units": 2, "concise_description": "Historical development of computing, roles of the computer engineer, computer hardware and software components, and overview of computer engineering design.", "ordered_topics": ["Historical development of modern computing", "Computer engineering profession", "Roles and responsibilities of the computer engineer", "Career paths and development", "Overview of computer engineering design", "Computer devices and hardware", "Internet of Things and People (IoTP)", "Computer software components", "Central processing units", "Input/output devices", "Operating systems and languages"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "partially_verified"},
    {"course_code": "MEE 101", "official_title": "Introduction to Mechanical Engineering", "level": 100, "semester": None, "units": 1, "concise_description": "Historical development of mechanical engineering, philosophy and scope, special fields, linkage to other disciplines, and role of mechanical engineers in society.", "ordered_topics": ["Historical development of mechanical engineering", "Philosophy and scope of contemporary mechanical engineering", "Overview of applied (solid) mechanics", "Overview of fluid and thermal engineering", "Thermodynamics and heat transfer", "Industrial and production engineering", "Engineering management sciences", "Linkage to other engineering disciplines and sciences", "Concept of innovation", "Applications of mechanical engineering", "Role of mechanical engineers in society", "Professional ethical responsibility", "Climate change and renewable energy"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "MME 102", "official_title": "Introduction to Materials and Metallurgical Engineering", "level": 100, "semester": None, "units": 2, "concise_description": "Historical development, role of metals in civilization, classification of metals, extractive, physical and mechanical metallurgy, and the Nigerian metallurgical industry.", "ordered_topics": ["Historical development of Materials and Metallurgical Engineering", "Difference between materials and metallurgical engineering", "Role of materials and metal products in human civilization", "Stone age, copper age, iron age, nuclear age, ICT age", "Study of the Periodic Table and classification of metals", "Process (extractive) metallurgical engineering", "Roasting, calcination, agglomeration, smelting and refining", "Physical metallurgical engineering", "Structure-property-application relationship", "Mechanical metallurgical engineering", "Stress-strain relationship and application", "Properties of ceramics, metals, polymers and composites", "Ferrous and non-ferrous materials industries", "Nigerian materials and metallurgical industry"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "PGE 101", "official_title": "Introduction to Petroleum and Gas Industry", "level": 100, "semester": None, "units": 2, "concise_description": "Geophysical exploration methods, petroleum geology principles, drilling for oil and gas, production, processing, transportation and unconventional sources.", "ordered_topics": ["Geophysical methods of petroleum exploration", "Principles of petroleum geology", "Origin, formation, migration and entrapment of petroleum", "Oil and gas windows", "Drilling for oil and gas", "Oil and gas reservoir", "Oil and gas production", "Oil and gas processing", "Oil and gas transportation", "Unconventional sources: shale gas", "Gas hydrates and coalbed methane", "Landfill and biogas technology"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "TEL 102", "official_title": "Introduction to Electrical Engineering", "level": 100, "semester": None, "units": 2, "concise_description": "Electrical circuits, electrostatics, magnetism, circuit theorems, three phase systems, electric power, electrical machines and basic electronics.", "ordered_topics": ["Electrical circuits and quantities", "DC and AC signals and RMS values", "Electrostatics and capacitors", "Magnetism and electromagnetism", "Faraday's laws of electromagnetic induction", "Basic laws and theorems: Ohm's, Kirchhoff's, Thevenin, Superposition", "Delta/Star transformation", "Three phase systems", "Electric power and power factor", "Introduction to electrical machines", "Transformers", "Basic electronics: semiconductors and diodes", "Electrical measurement"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "GET 207", "official_title": "Applied Mechanics", "level": 200, "semester": None, "units": 3, "concise_description": "Forces, moments, equilibrium of structures, friction, centroids, kinematics of particles and rigid bodies, Newton's laws and momentum.", "ordered_topics": ["Forces, moments and couples", "Equilibrium of simple structures and machine parts", "Friction", "First and second moments of area", "Centroids", "Kinematics of particles in plane motion", "Kinematics of rigid bodies in plane motion", "Newton's laws of motion", "Kinetic energy and momentum analysis"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "BME 211", "official_title": "Human Anatomy I", "level": 200, "semester": None, "units": 2, "concise_description": "Cell biology, tissue structures, human histology, basic structure of the human body, skeleton, and regional anatomy of limbs, thorax and abdomen.", "ordered_topics": ["Overview of cell biology", "Tissue structures and human histology", "Basic structure of the human body", "Body planes and positions", "The skeleton", "Regional anatomy of the upper limb", "Regional anatomy of the lower limb", "Regional anatomy of the thorax", "Regional anatomy of the abdomen"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "BME 213", "official_title": "Human Physiology I", "level": 200, "semester": None, "units": 2, "concise_description": "Basic concepts in human physiology, cellular physiology, homeostasis, musculoskeletal, cardiovascular, respiratory and urinary systems.", "ordered_topics": ["Basic concepts in human physiology", "Cellular physiology", "Homeostasis", "Musculoskeletal system", "Cardiovascular system", "Respiratory system", "Urinary system"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "BME 214", "official_title": "General Biochemistry I", "level": 200, "semester": None, "units": 2, "concise_description": "Chemical elements, periodic table, chemical bonds, macromolecules, amino acids, proteins, carbohydrates, lipids, nucleic acids and metabolic pathways.", "ordered_topics": ["Review of general chemistry", "Chemical elements and the periodic table", "Electronic configuration and chemical bonds", "Metals, non-metals, acids and bases", "Carbon hybridization and covalent bonds", "Functional groups and water properties", "The cell and hierarchy of organisation", "Amino acids and proteins", "Carbohydrates and glycosidic bonds", "Fatty acids and lipids", "Nucleic acids and nucleotides", "Gene transcription and translation"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "BME 215", "official_title": "Human Genetics I", "level": 200, "semester": None, "units": 2, "concise_description": "Human heredity, DNA, genes, blood groups, human genome project, gene sequencing, and genetic disorders.", "ordered_topics": ["Human heredity: haploid and diploid chromosomes", "DNA and traits", "Genes and blood groups", "The Human Genome: definition of genome", "History of the Human Genome Project", "Gene sequencing", "Molecular organization and gene content", "Genetic coding", "Genomic variation in humans", "Genetic disorders: albinism, cystic fibrosis, dwarfism", "Sickle cell disease and colour blindness", "Haemophilia and Duchenne muscular dystrophy"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "CET 202", "official_title": "Basic Electronics", "level": 200, "semester": None, "units": 3, "concise_description": "Semiconductor devices, biasing techniques for transistor, FET, MOSFET and operational amplifiers, and analysis of output in different operating modes.", "ordered_topics": ["Free electron motion in electric and magnetic fields", "Electronic structure of matter", "Conductivity in crystalline solids", "Theory of energy bands in conductors and insulators", "Semiconductor devices basics", "Biasing techniques for transistors", "FET and MOSFET operation", "Operational amplifier modes", "Analysis of output in different operating modes", "Design issues and limitations of semiconductor devices"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "partially_verified"},
    {"course_code": "EEE 208", "official_title": "Electrical Engineering Materials", "level": 200, "semester": None, "units": 3, "concise_description": "Atomic structure and bonding, crystal structure, properties of materials, electron motion, semiconductors, and discrete device fabrication.", "ordered_topics": ["Atomic structure and bonding", "Crystal structure and defects", "Properties of materials", "Free electron motion in electric and magnetic fields", "Electronic structure of matter", "Conductivity in crystalline solids", "Energy bands in conductors, insulators and semiconductors", "Electrons in metals and electron emissions", "Carriers and transport phenomena in semiconductors", "Characteristics of diodes and transistors", "Photocells and light emitting diodes", "Discrete device fabrication and IC technology"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "TEL 202", "official_title": "Applied Electricity II", "level": 200, "semester": None, "units": 3, "concise_description": "Power factor, AC circuits, DC machines, single phase transformers, three phase induction motors, and electrical power system structure.", "ordered_topics": ["Power factor and power in AC circuits", "Resonance in RLC series and parallel circuits", "Three phase circuits and phasor diagrams", "DC machines: construction and winding concepts", "DC generators: principle and EMF equation", "DC motors: torque and speed characteristics", "Single phase transformers: construction and operation", "Transformer losses and efficiency", "Three phase induction motors", "Torque-slip characteristics", "General structure of electrical power systems", "Earthing and electrical wiring practice"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "MEE 207", "official_title": "Applied Mechanics", "level": 200, "semester": None, "units": 3, "concise_description": "Forces, moments, equilibrium of simple structures, friction, centroids, kinematics and Newton's laws of motion.", "ordered_topics": ["Forces, moments and couples", "Equilibrium of simple structures and machine parts", "Friction", "First and second moments of area", "Centroids", "Kinematics of particles in plane motion", "Kinematics of rigid bodies in plane motion", "Newton's laws of motion", "Kinetic energy and momentum analysis"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "partially_verified"},
    {"course_code": "PGE 201", "official_title": "Petroleum Geology", "level": 200, "semester": None, "units": 3, "concise_description": "Earth structure, origin and accumulation of petroleum, trapping mechanisms, subsurface maps and petroleum geology of Nigerian sedimentary basins.", "ordered_topics": ["Earth structure and depositional systems", "Origin and maturation of petroleum", "Migration and accumulation of petroleum", "Trapping mechanisms", "Abnormal pressure", "Petroleum prospecting and tools", "Uses of geological data", "Reservoir rocks and fluids", "Subsurface maps and correlation principles", "Petroleum as a resource", "Geology of the Niger Delta", "Geology of the Chad Basin", "Geology of the Anambra Basin", "Geologic field trip"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "CEE 301", "official_title": "Fluid Mechanics", "level": 300, "semester": None, "units": 3, "concise_description": "Incompressible viscous flow, laminar and turbulent flows, boundary layer theory, pipe network analysis, potential flows and water hammer.", "ordered_topics": ["Introduction to incompressible viscous flow", "Laminar and turbulent flows", "Reynolds number", "Boundary layer flow, lift and drag", "Laminar flow in pipes and between parallel plates", "Turbulent flows in ducts and pipes", "Physical hydraulic models", "Interconnected pipes and pipe network analysis", "Potential flows and flow nets", "Steady and unsteady flow in closed conduits", "Water hammer and surge tanks"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "CEE 302", "official_title": "Strength of Structural Materials", "level": 300, "semester": None, "units": 2, "concise_description": "Bending theory, failure theories, creep, fatigue, springs, thin and thick cylinders, rotating disks and multi-dimensional stress systems.", "ordered_topics": ["Advanced topics on axial and lateral loading of shafts and beams", "Torsional loading of shafts and beams", "Slope and deflection of beams", "Unsymmetrical bending and shear centre", "Springs", "Creep and fatigue", "Fracture and stress concentration", "Stresses in thin and thick cylinders", "Rotating disks", "Multi-dimensional stress systems", "Mohr's circle and failure theories"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "CEE 303", "official_title": "Engineering Geology", "level": 300, "semester": None, "units": 2, "concise_description": "Geological structures and mapping, rocks and minerals, stratigraphy, geology of Nigeria, and engineering applications to water supply and site investigation.", "ordered_topics": ["Geological structures and mapping", "Rocks and minerals", "Stratigraphy and time scale", "Fossils and their importance", "Introduction to the geology of Nigeria", "Engineering applications: water supply", "Site investigations for dams and dykes", "Geological hazards and slope processes", "Earthquakes and subsidence", "Engineering properties of geologic materials", "Preparation of engineering geology reports"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "CEE 304", "official_title": "Civil Engineering Materials", "level": 300, "semester": None, "units": 3, "concise_description": "Concrete technology, steel technology, timber technology, and properties of rubber, plastics, asphalt, glass, lime and bricks for civil engineering.", "ordered_topics": ["Concrete technology: types of cements and aggregates", "Concrete mix design and properties", "Steel technology: production and fabrication", "Corrosion and its prevention", "Tests on steel and quality control", "Timber technology: types of wood and properties", "Timber defects, stress grading and preservation", "Rubber and plastics", "Asphalt and tar", "Glass, lime and bricks", "Applications to buildings, roads and bridges"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "CEE 305", "official_title": "Soil Mechanics I", "level": 300, "semester": None, "units": 3, "concise_description": "Mineralogy of soils, soil classification, engineering properties, permeability, Atterberg limits, shear strength, compaction and consolidation.", "ordered_topics": ["Mineralogy of soils and soil structures", "Formation of soils", "Soil classification", "Engineering properties of soils", "Soil-water relationships: void ratio and porosity", "Specific gravity and permeability", "Atterberg limits", "Particle size distribution", "Shear strength of soils and Mohr's stress circle", "Compaction and soil stabilisation", "Settlement and theory of consolidation", "Laboratory work"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "CEE 306", "official_title": "Design of Structures I", "level": 300, "semester": None, "units": 2, "concise_description": "Fundamentals of design process, materials selection, building regulations, elastic design and limit state design of reinforced concrete elements.", "ordered_topics": ["Fundamentals of design process", "Materials selection", "Building regulations and codes of practice", "Design philosophy", "Elastic design", "Limit state design", "Design of structural elements in reinforced concrete"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "CEE 307", "official_title": "Structural Mechanics I", "level": 300, "semester": None, "units": 2, "concise_description": "Analysis of determinate structures, structural analysis theorems, influence lines, deflection of determinate structures, and indeterminate structures.", "ordered_topics": ["Analysis of determinate structures: beams and trusses", "Structural analysis theorems", "Graphical methods", "Application to simple determinate trusses", "Influence lines", "Williot-Mohr diagram", "Deflection of statically determinate structures", "Unit load method", "Moment-area methods", "Strain energy methods", "Introduction to statically indeterminate structures"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "CEE 308", "official_title": "Engineering Surveying and Photogrammetry I", "level": 300, "semester": None, "units": 2, "concise_description": "Chain surveying, compass surveying, contours, traversing, levelling, tachometry and introduction to photogrammetry.", "ordered_topics": ["Chain surveying", "Compass surveying methods", "Contours and their uses", "Traversing: methods and applications", "Levelling: geodetic levelling", "Errors in levelling and their adjustments", "Tachometry: methods and substance heighting", "Self-adjusting and electromagnetic methods", "Introduction to photogrammetry"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "CPE 301", "official_title": "Computer Organisation and Architecture", "level": 300, "semester": None, "units": 3, "concise_description": "Computer fundamentals, Von-Neumann and Harvard architecture, computer arithmetic, memory systems, control unit, instruction sets and operating systems.", "ordered_topics": ["Computer fundamentals and development history", "Hard-wired vs stored program concept", "Von-Neumann and Harvard architecture", "Computer arithmetic: integer and floating-point", "Arithmetic and logic unit (ALU)", "CISC and RISC architecture", "Storage and input/output systems", "Memory system and cache memory", "Control unit: micro-operations and micro-programmed control", "Instruction set and register organisation", "High performance computer systems and pipelining", "Overview of operating systems"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "CPE 302", "official_title": "Measurement and Instrumentation", "level": 300, "semester": None, "units": 3, "concise_description": "Transducers, basic meters, DC and AC bridges, electronic instruments, oscilloscopes, signal analysers and measurement of physical quantities.", "ordered_topics": ["Transducers and applications", "General instrumentation", "Basic meters in DC measurement", "Basic meters in AC measurements", "Rectifier and electronic voltmeters", "Electro-dynamometer and wattmeter", "Instrument transformers", "DC and AC bridges and their applications", "Electronic instruments for voltage, current and resistance", "Digital voltmeters", "Oscilloscope: vertical and horizontal deflection systems", "Electronic function generators"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "CPE 307", "official_title": "Assembly Language Programming", "level": 300, "semester": None, "units": 2, "concise_description": "Language abstraction, machine code, Intel 8086 assembly language programming, assembler directives, modular programming and interrupts.", "ordered_topics": ["Language level of abstraction", "Characteristics and advantages of machine code", "Instruction set and dependency on processor", "Intel 8086 programming model", "Addressing modes and instruction format", "Instruction set: arithmetic and logical", "String and branching instructions", "Program control and machine control", "Assembler directives and hand-assembling", "Modular programming", "Interrupt and service routine", "Interfacing assembly language to C", "Introduction to MMX and SSE programming"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "EEE 311", "official_title": "Electric Circuit Theory I", "level": 300, "semester": None, "units": 2, "concise_description": "Passive circuit elements, circuit theorems, network response, Laplace transform, transfer functions, resonance and two-port analysis.", "ordered_topics": ["Passive circuit elements: R, L, C and transformers", "Circuit theorems: Ohm's, KVL, KCL", "Loop current and node potential methods", "Superposition theorem", "Network response to step, ramp and impulses", "Network functions and response to exponential sources", "Laplace transform and transfer functions", "Pole-zero configuration", "Resonance", "Two-port analysis and parameters"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "EEE 321", "official_title": "Analogue Electronic Circuits", "level": 300, "semester": None, "units": 2, "concise_description": "Single-stage transistor amplifiers, operational amplifiers, feedback amplifiers, power amplifiers and voltage stabilizing circuits.", "ordered_topics": ["Single-stage transistor amplifiers using BJT", "Single-stage transistor amplifiers using FET", "Equivalent circuits and calculation of current gain", "Voltage gain and power gain calculations", "Input and output impedance", "Operational amplifiers: description and parameters", "Operational amplifier applications", "Feedback amplifiers", "Broadband and narrowband amplifiers", "Power amplifiers", "Voltage and current stabilizing circuits", "Multi-stage amplifiers using BJTs and FETs"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "EEE 322", "official_title": "Digital Electronic Circuits", "level": 300, "semester": None, "units": 2, "concise_description": "Number systems, logic gates, Boolean algebra, Karnaugh maps, combinational circuits, flip-flops, counters, registers and multivibrators.", "ordered_topics": ["Number systems and codes", "Logic gates", "Simplification using Boolean algebra", "Simplification using Karnaugh method", "Design of combinational circuits", "Flip-flops", "Application of flip-flops in counters", "Registers and timers", "Switching and wave shaping circuits", "Generation of non-sinusoidal signals (multivibrators)", "Introduction to ADC and DAC", "Design of logic gates (Diode, DTL, TTL, ECL)", "Introduction to microprocessors"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "EEE 324", "official_title": "Electromagnetic Fields and Waves I", "level": 300, "semester": None, "units": 2, "concise_description": "Electromagnetic laws, electrostatic fields, magnetic fields, Maxwell's equations, wave propagation and skin effect.", "ordered_topics": ["Review of electromagnetic laws in integral form", "Gauss's law", "Ampere's and Faraday's laws", "Electrostatic fields due to distribution of charge", "Magnetic fields in and around current carrying conductors", "Time-varying magnetic and electric fields", "Conduction and displacement current", "Maxwell's equations in rectangular coordinates", "Electromagnetic potential and waves", "Poynting vector and boundary conditions", "Wave propagation in good conductors and skin effect", "Plane waves in unbounded dielectric media"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "EEE 326", "official_title": "Electric Circuit Theory II", "level": 300, "semester": None, "units": 2, "concise_description": "Non-linear circuit analysis, network functions, circuit synthesis, Foster and Cauer synthesis, and active and passive filter design.", "ordered_topics": ["Non-linear circuit analysis", "Network functions and locus diagrams", "Circuit synthesis: realisability criteria", "Foster and Cauer syntheses of RC, RL, LC and RLC circuits", "Filters: design and operation", "Low-pass and high-pass filters", "Bandpass filters", "Butterworth filter design", "Chebychev filter design", "Active network analysis and synthesis"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "MME 301", "official_title": "Thermodynamics of Materials", "level": 300, "semester": None, "units": 2, "concise_description": "Thermochemistry, phase diagrams, heterogeneous equilibrium, solutions, electrochemical thermodynamics and application to metallurgical systems.", "ordered_topics": ["Thermochemistry applied to metallurgical reactions", "Graphical representations of equilibria", "Binary and ternary phase diagrams", "Heterogeneous equilibrium", "Behaviour of solutions and standard states", "Electrochemical thermodynamics", "Application of thermodynamic data to predict stable phases", "Construction and use of partial pressure diagrams", "Eh-pH diagrams", "Temperature-composition diagrams", "Activities and equilibria in slag-metal systems", "Gas-metal systems"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "MME 304", "official_title": "Chemistry of Materials", "level": 300, "semester": None, "units": 2, "concise_description": "Basic inorganic chemistry of materials, chemical properties, structure and bonding of solids, thermochemistry, kinetics and reactor design.", "ordered_topics": ["Basic inorganic chemistry of materials", "Chemical properties, structure and bonding of solids", "Energy, enthalpy and entropy", "Thermochemistry", "Kinetics and rate processes", "Application of chemistry principles to materials engineering", "Flowsheeting", "Reactor design", "Materials and metals processing", "Environmental considerations"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "MME 305", "official_title": "Engineering Materials: Structure and Properties", "level": 300, "semester": None, "units": 2, "concise_description": "Structure and properties of metals, ceramics, polymers and composites, and structure-property relationships in engineering materials.", "ordered_topics": ["Basic structure of ceramics", "Basic structure of alloys", "Basic structure of composites", "Basic structure of metals", "Basic structure of polymers", "Structure-property relationships", "Mechanical properties of materials", "Electrical properties of materials", "Magnetic properties of materials", "Thermal properties of materials", "Chemical properties of materials"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "MME 312", "official_title": "Physical Metallurgy I", "level": 300, "semester": None, "units": 2, "concise_description": "Metallurgical reactions, iron-carbon diagrams, steel and cast iron classification, heat treatment, alloying and hardening processes.", "ordered_topics": ["Introduction to metals and metal alloy systems", "The metallic bond and structure of metals", "Solidification of pure metals", "Nucleation and growth processes", "Preparation of materials to reveal structure", "Annealing of metals and grain growth", "Deformation, slip and twinning", "Binary equilibria and alloying", "Equilibrium phase diagrams and the Lever rule", "Iron-iron carbide diagram and hysteresis", "Martensite, quenching and TTT curves", "Hardenability, bainite and alloying", "Tempering properties and structure", "High alloy steels and cast irons"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "PNG 308", "official_title": "Drilling and Well Design I", "level": 300, "semester": None, "units": 3, "concise_description": "Drilling engineering fundamentals, well planning and cost estimation, drilling rigs and systems, bit selection, drilling fluids and hydraulics.", "ordered_topics": ["Introduction to drilling engineering", "Fundamental concepts in oil well drilling", "Well planning and cost estimation", "Drilling team and drilling rigs", "Rig power system and hoisting system", "Circulation system and rotary system", "Well control system and well-monitoring system", "Special marine equipment", "Drilling cost analysis", "Bit types and rock failure mechanisms", "Bit selection and evaluation", "Factors affecting tooth wear and bearing wear", "Drilling fluids and drilling hydraulics", "Well head equipment"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "PNG 310", "official_title": "Fundamentals of Reservoir Engineering", "level": 300, "semester": None, "units": 3, "concise_description": "Reservoir characterisation, hydrocarbon in-place determination, material balance, water influx models, fluid flow concepts and decline curve analysis.", "ordered_topics": ["Functions of a reservoir engineer", "Characteristics of petroleum reservoir", "Geological concepts in reservoir engineering", "Recovery methods and definitions of reservoirs", "Determination of hydrocarbon in-place: volumetric methods", "Material balance and applications", "Water influx models and calculations", "Uncertainties in reserve calculations", "Fluid flow concepts and flow potential", "Darcy's Law", "Decline curve analysis"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "PNG 312", "official_title": "Oil and Gas Production Engineering I", "level": 300, "semester": None, "units": 3, "concise_description": "Subsurface and surface production operations, nodal analysis, inflow performance relationship, problem wells analysis, well stimulation and artificial lift.", "ordered_topics": ["Introduction to petroleum engineering: subsurface and surface operations", "Functions of subsurface production engineer", "Nodal analysis in flow and outflow performances", "Governing equations and inflow performance relationship (IPR)", "Productivity index, formation damage and skin effect", "Vertical lift well head equipment performance", "Choke performance", "Problem wells analysis: sand, water and hydrate", "Scale, unstable flow and waxy crude production", "Well surveillance", "Well stimulation: fracturing and acidising", "Introduction to artificial lift methods", "Gas lift and pumping system"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "SSG 321", "official_title": "Continuum Mechanics I", "level": 300, "semester": None, "units": 2, "concise_description": "Mathematical preliminaries for continuum mechanics, tensor theory, kinematics, and differential and integral formulations of governing equations.", "ordered_topics": ["Mathematical preliminaries for continuum mechanics", "Linear independence and basis vectors", "The Einstein summation convention", "Scaling, scalar, vector and tensor products", "Cartesian and curvilinear orthogonal coordinate systems", "Tensors as linear transformations", "Tensor invariants", "Additive and multiplicative decompositions", "Differentiation of vectors and tensors", "Gradient, divergence and curl", "Integral theorems of Stokes and Gauss", "Thermodynamic laws"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
    {"course_code": "SSG 322", "official_title": "Control Theory I", "level": 300, "semester": None, "units": 2, "concise_description": "Dynamic systems, time and frequency domain modelling, state space representations, transfer functions, stability analysis and feedback control design.", "ordered_topics": ["Dynamic systems", "Time domain and frequency domain modelling", "Response analysis of linear control systems", "State space representations", "The exponential matrix and transfer functions", "Time response analysis of linear second order systems", "Routh's method for BIBO stability", "Steady state error analysis", "Design of feedback control systems", "Discrete time analysis for digital control systems"], "prerequisites": None, "recommended_textbooks": [], "evidence_url": "https://www.nuc.edu.ng/wp-content/uploads/2022/12/Engineering-CCMAS.pdf", "verification_status": "verified"},
]


def main():
    result = supabase.table("course_outlines").upsert(
        OUTLINES,
        on_conflict="course_code",
    ).execute()

    written = len(result.data or [])
    print(f"Course outlines upserted: {written}")
    print(f"Expected: {len(OUTLINES)}")
    if written != len(OUTLINES):
        print("WARNING: written count does not match expected count — check for errors above.")


if __name__ == "__main__":
    main()