begin;

alter table public.materials
  add column if not exists material_priority text not null default 'unreviewed';

alter table public.materials
  drop constraint if exists materials_material_priority_check;

alter table public.materials
  add constraint materials_material_priority_check
  check (
    material_priority in (
      'start_here',
      'core',
      'recommended',
      'supplementary',
      'reference',
      'unreviewed'
    )
  );

alter table public.materials
  add column if not exists priority_reason text;

alter table public.materials
  add column if not exists priority_source text not null default 'unreviewed';

alter table public.materials
  drop constraint if exists materials_priority_source_check;

alter table public.materials
  add constraint materials_priority_source_check
  check (priority_source in ('unreviewed', 'manual_review'));

alter table public.materials
  add column if not exists priority_updated_at timestamptz;

create table if not exists public.material_review_log (
  id bigint generated by default as identity primary key,
  material_id bigint not null references public.materials(id) on delete cascade,
  previous_category text,
  new_category text,
  previous_priority text,
  new_priority text,
  review_reason text,
  reviewed_at timestamptz not null default now()
);

create index if not exists material_review_log_material_id_idx
  on public.material_review_log (material_id, reviewed_at desc);

alter table public.material_review_log enable row level security;

commit;
