begin;

alter table public.courses
  add column if not exists department text,
  add column if not exists catalogue_source text not null default 'existing_catalogue',
  add column if not exists verification_status text not null default 'verified';

alter table public.courses
  drop constraint if exists courses_verification_status_check;

alter table public.courses
  add constraint courses_verification_status_check
  check (verification_status in ('verified', 'partially_verified', 'unverified'));

update public.courses
set department = case
  when code like 'TCH %' then 'Chemical Engineering'
  else 'Shared Engineering'
end
where department is null;

alter table public.materials
  add column if not exists source_name text,
  add column if not exists material_summary text,
  add column if not exists resource_kind text not null default 'document';

alter table public.materials
  drop constraint if exists materials_resource_kind_check;

alter table public.materials
  add constraint materials_resource_kind_check
  check (resource_kind in ('document', 'external_course', 'video_course', 'website'));

create table if not exists public.material_submissions (
  id bigint generated by default as identity primary key,
  course_code text not null,
  title text not null,
  url text not null,
  category text not null default 'references',
  note text,
  submitted_by uuid references auth.users(id) on delete set null,
  status text not null default 'pending',
  review_note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint material_submissions_category_check check (
    category in (
      'lecture_notes', 'slides', 'past_questions', 'assignments',
      'laboratory', 'practice', 'textbooks', 'references', 'other'
    )
  ),
  constraint material_submissions_status_check check (
    status in ('pending', 'approved', 'rejected', 'duplicate')
  )
);

alter table public.material_submissions enable row level security;

drop policy if exists "Students can submit materials" on public.material_submissions;
create policy "Students can submit materials"
on public.material_submissions
for insert
to authenticated
with check (submitted_by = auth.uid() and status = 'pending');

drop policy if exists "Students can read their material submissions" on public.material_submissions;
create policy "Students can read their material submissions"
on public.material_submissions
for select
to authenticated
using (submitted_by = auth.uid());

commit;
